services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: link_shortener_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: link_shortener
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d link_shortener"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: link_shortener_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  data:

