services:
  postgres:
    image: postgres:16.4-alpine3.20
    container_name: order_simple_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_pass
      POSTGRES_DB: order_simple
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d order_simple"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  data:

