env: "local"
db_storage: "./postgres-data"
http_server:
  address: "http://localhost:8081"
  timeout: 4s
  idle_timeout: 60s
mail_service:
  email: "test@example.com"
  password: "any-password"
  host: "localhost"
  port: "1025"
  address: "localhost:1025"
